# Generated by Django 4.2.1 on 2023-05-21 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_userdetails_delete_shippingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
